language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run -m unittest discover -s tests -t tests
after_success:
- coveralls